/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerLapor;
import javax.swing.JButton;
import javax.swing.JTextField;



/**
 *
 * @author rizqi
 */
public class Lapor extends javax.swing.JPanel {
    
    ControllerLapor cl;

    /**
     * Creates new form Lapor
     */
    public Lapor() {
        initComponents();
         
        cl = new ControllerLapor(this);       // controller buat panel Lapor
        Histori historiPanel = new Histori(); // bikin panel Histori di sini
        cl.setHistory(historiPanel);          // set agar tidak null
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_lokasi = new javax.swing.JTextField();
        tf_tanggal = new javax.swing.JTextField();
        tf_deskripsi = new javax.swing.JTextField();
        tf_waktu = new javax.swing.JTextField();
        btn_kirim = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jPopupMenu1.setToolTipText("Laporan Berhasil dikirim");

        setBackground(new java.awt.Color(241, 241, 241));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lokasi ");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Waktu");

        jLabel6.setText("Deskripsi");

        tf_lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lokasiActionPerformed(evt);
            }
        });

        tf_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tanggalActionPerformed(evt);
            }
        });

        btn_kirim.setText("Kirim");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });

        btnReset.setText("Batal");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(29, 29, 29)
                        .addComponent(btn_kirim))
                    .addComponent(tf_tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addComponent(tf_lokasi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_waktu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_deskripsi))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(tf_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kirim)
                    .addComponent(btnReset))
                .addContainerGap(287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lokasiActionPerformed

    private void tf_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tanggalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cl.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        cl.insert();
        cl.isiTable();
        cl.reset();
    }//GEN-LAST:event_btn_kirimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField tf_deskripsi;
    private javax.swing.JTextField tf_lokasi;
    private javax.swing.JTextField tf_tanggal;
    private javax.swing.JTextField tf_waktu;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return btn_kirim;
    }

    public void setjButton1(JButton jButton1) {
        this.btn_kirim = jButton1;
    }

    public JTextField getTf_deskripsi() {
        return tf_deskripsi;
    }

    public void setTf_deskripsi(JTextField tf_deskripsi) {
        this.tf_deskripsi = tf_deskripsi;
    }

    public JTextField getTf_lokasi() {
        return tf_lokasi;
    }

    public void setTf_lokasi(JTextField tf_lokasi) {
        this.tf_lokasi = tf_lokasi;
    }

    public JTextField getTf_tanggal() {
        return tf_tanggal;
    }

    public void setTf_tanggal(JTextField tf_tanggal) {
        this.tf_tanggal = tf_tanggal;
    }

    public JTextField getTf_waktu() {
        return tf_waktu;
    }

    public void setTf_waktu(JTextField tf_waktu) {
        this.tf_waktu = tf_waktu;
    }
}
